### ISSUE TITLE
Inconsistent Digging Behavior

### ISSUE THREAD

**Issue by ImpalerWrG** [ImpalerWrG/Khazad#5]
Dwarves will become glitched sometimes when involved in Digging, they can freeze up and never move again after finishing the digging, before doing any digging and sometimes the whole dig designation is ignored

**Comment by calmofthestorm** [comment]
I ran into this with the recent tech demo.

**Comment by ImpalerWrG** [comment]
Fixed (though likely not forever) in https://github.com/ImpalerWrG/Khazad/commit/96287deddaa7455d198f4d9a01514614c5bcb62d
